version: '3'
services:
  api:
    image: crudapi
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    container_name: api
    command: npm run dev
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8080:3000"
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    command: mysqld --user=root --verbose
    volumes:
       - ./schemadump.sql:/docker-entrypoint-initdb.d/schemadump.sql
    ports:
      - "3336:3306"
    environment:
      MYSQL_DATABASE: "test"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"